config/routes.rb
Rails.application.routes.draw do
  devise_for :podcasts
 root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PodcastFm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if alert %>
    <p class="alert">
      <%= alert %>
    </p>
  <% elsif notice %>
    <p class="notice">
      <%= notice %>
    </p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div id="background">
  <header class="cf">
    <div class="wrapper_wide">
      <a href="#" id="logo">podcast.fm</a>
      <nav>
        <ul>
          <% unless podcast_signed_in? %>
            <li><%= link_to "Sign In", new_podcast_session_path %></li>
            <li>  <%= link_to "Create a Podcast", new_podcast_registration_path %></li>
          <% else %>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Explore</a></li>
            <li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %></li>

          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <!-- buttons and call to action -->
  <div class="wrapper_skinny">
    <h1>Discover your new favorite <br> podcast, or create your own.</h1>
    <%= link_to "Create a Podcast", new_podcast_registration_path, class: "button button_highlight" %>
    <a href="#" class="button button_white">Explore</a>
  </div>
</div>